//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubeCalificaciones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TP_20191CEntities : DbContext
    {
        public TP_20191CEntities()
            : base("name=TP_20191CEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<RespuestaAlumno> RespuestaAlumno { get; set; }
        public virtual DbSet<ResultadoEvaluacion> ResultadoEvaluacion { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
    }
}
